// Literal error `code` strings customer.service.js / customer.repository.js
// actually return (grepped from those files directly — see git blame
// for the exact lines checked at the time), same convention as
// lib/errorCodes.ts for auth.
export const CUSTOMER_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  B2B_REQUIRED_FIELDS: "B2B_REQUIRED_FIELDS",
  B2C_REQUIRED_FIELDS: "B2C_REQUIRED_FIELDS",
  GSTIN_STATE_MISMATCH: "GSTIN_STATE_MISMATCH",
  CUSTOMER_GSTIN_ALREADY_EXISTS: "CUSTOMER_GSTIN_ALREADY_EXISTS",
  CUSTOMER_PHONE_ALREADY_EXISTS: "CUSTOMER_PHONE_ALREADY_EXISTS",
  CUSTOMER_ARCHIVED_EXISTS: "CUSTOMER_ARCHIVED_EXISTS",
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  CONTACTS_B2B_ONLY: "CONTACTS_B2B_ONLY",
  CONTACT_PRIMARY_CONFLICT: "CONTACT_PRIMARY_CONFLICT",
  INVALID_FORMAT: "INVALID_FORMAT",
} as const;
